[Quart]
DEBUG=1

[Pars]
    [Pars.21vek]
    main_api_url="https://www.21vek.by/search/?sa=&term={query}"

    [Pars.Onliner]
    main_api_url="https://www.onliner.by/sdapi/catalog.api/search/products?query={query}"

    [Pars.Kufar]
    main_pars_url="https://api.kufar.by/search-api/v2/search/rendered-paginated?cnd=2&lang=ru&ot=1&query={query}&search_variant=constant_score&size=43&sort=scr.d"

    [Pars.MMG]
    main_pars_url="https://mmg.by/search/?q={query}"